stages:
  - deploy

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"

deploy:
  tags:
    - FolioFrame
  stage: deploy
  image: python:3.9
  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install ansible
  script:
    - ansible-playbook deploy.yml -vvv
  only:
    - main
  artifacts:
    expire_in: 1 second