- name: Deploy
  hosts: local
  vars:
    dest_path: "{{ lookup('env', 'DEST_PATH') }}"
    remote_deploy_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
  become: true
  become_user: "{{ remote_deploy_user }}"
  tasks:
    - name: Pull latest version
      ansible.builtin.git:
        repo: 'git@gitlab.com:gabibdods/folioframe.git'
        dest: "{{ dest_path }}"
        version: main
        force: yes
        update: yes

    - name: Collect static files as www-data
      become: true
      become_user: www-data
      args:
        chdir: "{{ dest_path }}"
      command: "./foliovenv/bin/python folioframe/manage.py collectstatic --noinput --clear"

    - name: Reload systemd
      become: true
      become_user: root
      command: systemctl daemon-reload

    - name: Restart Gunicorn
      become: true
      become_user: root
      systemd:
        name: gunicorn
        state: restarted

    - name: Test Nginx config
      become: true
      become_user: root
      command: nginx -t

    - name: Restart Nginx
      become: true
      become_user: root
      systemd:
        name: nginx
        state: restarted
        
    - name: sudo update
      become: true
      become_user: root
      command: apt update
        
    - name: sudo upgraded
      become: true
      become_user: root
      command: apt upgrade -y