services:
  ffdb:
    image: postgres:16
    container_name: ffdb
    env_file: [.env]
    expose: ["5432"]
    volumes:
      - pg_data:/var/lib/postgres/data
    restart: unless-stopped
    networks: [gabibdods]

  ffdj:
    build: .
    container_name: ffdj
    env_file: [.env]
    expose: ["8000"]
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on: [ffdb]
    restart: unless-stopped
    networks: [gabibdods]

  ffnx:
    image: nginx:1.27-alpine
    container_name: ffnx
    expose: ["80"]
    volumes:
      - ./docker/nginx/nginx.d:/etc/nginx/nginx.d
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/update_cloudflare_ips.sh:/app/update_cloudflare_ips.sh:ro
      - ./docker/nginx/40-update-cloudflare-ips.sh:/docker-entrypoint.d/40-update-cloudflare-ips.sh:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on: [ffdj]
    restart: unless-stopped
    networks: [gabibdods]

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  gabibdods:
    external: true
