#!/usr/bin/env sh
set -euo pipefail

CONF="/etc/nginx/conf.d/cloudflare_ips.conf"
BACKUP="${CONF}.bkp"
TMP="$(mktemp)"

{
    echo "# Autogenerated from https://www.cloudflare.com/ips-v4: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    echo "allow 127.0.0.1;"
    curl -fsSL https://www.cloudflare.com/ips-v4 | awk '{print "allow "$1";"}'
} > "$TMP"

if [ -f "$CONF" ]; then cp "$CONF" "$BACKUP"; fi
cp "$TMP" "$CONF"

if nginx -t >/dev/null 2>&1; then
    if [ -f /run/nginx.pid ] && [ -s /run/nginx.pid ]; then
        nginx -s reload
    else
        echo "Skipping nginx reload."
    fi
else
    if [ -f "$BACKUP" ]; then cp "$BACKUP" "$CONF"; fi
    exit 1
fi

rm -f "$TMP"
