#!/usr/bin/env sh
set -euo

CONF="/etc/nginx/conf.d/cloudflare_ips.conf"
BAKP="${CONF}.bkp"
TMP="$(mktemp)"

mkdir -p "$(dirname "$CONF")"

{
    echo "# Autogenerated from https://www.cloudflare.com/ips-v4: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    echo "allow 127.0.0.1;"
    echo "allow 172.18.0.5;"
    curl -fsSL https://www.cloudflare.com/ips-v4 | awk '{print "allow "$1";"}'
} > "$TMP"

if [ -f "$CONF" ] && [ ! -f "$BAKP" ]; then
	cp "$CONF" "$BAKP";
fi

mv -f "$TMP" "$CONF"

if nginx -t >/dev/null 2>&1; then
    if [ -s /run/nginx.pid ]; then
        nginx -s reload
    fi
else
    [ -f "$BAKP" ] && cp -f "$BAKP" "$CONF"
fi

rm -f "$TMP"
